export const assets = {
  wall_ground: "block/wall_ground.png",
  shrub: "block/shrub.png",
  high_grass: "block/high_grass.png",
  door: "block/door.png",
  locked_door: "block/locked_door.png",
  empty: "block/empty.png",
  iron_maker: "block/iron_maker.png",
  wall_deco: "block/wall_deco.png",
  pedestal: "block/pedestal.png",
  empty_deco: "block/empty_deco.png",
  empty_sp: "block/empty_sp.png",
  well: "block/well.png",
  bookshelf: "block/bookshelf.png",
  statue: "block/statue.png",
  secret_door: "block/secret_door.png",
  water: "block/water0.png",
  alchemy: "block/alchemy.png",
  statue_sp: "block/statue_sp.png",
  tent: "block/tent.png",
  bed: "block/bed.png",
  embers: "block/embers.png",
  glass_wall: "block/glass_wall.png",

  tiles_town: "tiles/tiles_town.png",
  // water0: "block/water0.png",
};